#!/usr/bin/env bash
# Writes docker-compose.kin-deploy-host.yml next to docker-compose.yml.
# Maps the public Kin hostname to host-gateway so the nextcloud container can
# reach https://<hostname>/... (OIDC discovery) on the same host without hairpin NAT.
set -euo pipefail

MODULE_ROOT="${1:?module root directory}"
HOST="${2:?Kin hostname from /etc/kin/config.ini}"

if [[ ! "${HOST}" =~ ^[a-zA-Z0-9._-]+$ ]]; then
  echo "write-compose-host-overlay: invalid hostname: ${HOST}" >&2
  exit 1
fi

OVERLAY="${MODULE_ROOT}/docker-compose.kin-deploy-host.yml"
TMP="${OVERLAY}.$$"

cat > "${TMP}" <<EOF
# Generated by write-compose-host-overlay.sh — do not edit by hand.
version: '3.8'
services:
  nextcloud:
    extra_hosts:
      - "${HOST}:host-gateway"
EOF

mv -f "${TMP}" "${OVERLAY}"
